Adding sound to game.
cagdasgerede/JavaSnake pull request #12
Opened 2020-12-10 10:54 UTC by yasemindmrts

2020-12-12 14:30 UTC, cagdasgerede commented
Bir dahaki sefere beni Reviewer olarak eklemeyi unutma. Ayrıca Assignees kısmında bana atama yapmamışsın. Bir daha ki dönüşte bu atamayı da yap.

2020-12-12 14:30 UTC, cagdasgerede commented on src/main/java/pl/nogacz/SoundManager.java
> +}
add new line

2020-12-12 14:31 UTC, cagdasgerede commented on src/main/java/pl/nogacz/SoundManager.java
> +
Gereksiz newline boşlukları var burada.

2020-12-12 14:33 UTC, cagdasgerede requested changes
Needs more work. See my comments in the code.

Yaptıklarını anlattığın bir videonun linkini PR threadinde paylaş.

Ayrıca yeni eklediğin davranışlarla ilgili test yaz.

2020-12-12 14:33 UTC, cagdasgerede commented on src/main/java/pl/nogacz/SoundManager.java
> +public class SoundManager{
Bu kodu bir yerden mi aldın? Eğer öyleyse burada kaynak göster.

2020-12-19 07:37 UTC, cagdasgerede commented on build.gradle
> +	id 'java'
fix spacing

2020-12-19 07:37 UTC, cagdasgerede commented on src/main/java/pl/nogacz/snake/application/EndGame.java
> +
gereksiz newline

2020-12-19 07:37 UTC, cagdasgerede commented on src/main/java/pl/nogacz/snake/board/Board.java
> +            m= new SoundManager("sounds/GameSound.wav");
fix spacing

```m = new```

2020-12-19 07:38 UTC, cagdasgerede commented on src/main/java/pl/nogacz/snake/board/Board.java
> +            m= new SoundManager("sounds/GameSound.wav");
Şu şekilde constant tanımla ve burada bu constantı kullan:

private final static int GAME_SOUND = "sounds/GameSound.wav"

2020-12-19 07:38 UTC, cagdasgerede commented on src/main/java/pl/nogacz/snake/board/Board.java
> +        }catch(Exception e){
```} catch```

2020-12-19 07:39 UTC, cagdasgerede commented on src/main/java/pl/nogacz/snake/board/Board.java
> +                        SoundManager s = new SoundManager("sounds/EatFood.wav");
ayni sekilde bura icin de constant tanimla ve o constanti kullan:

private final static String EAT_FOOD_SOUND = "sounds/EatFood.wav";

2020-12-19 07:40 UTC, cagdasgerede commented on src/main/java/pl/nogacz/snake/board/Board.java
> +                        m= new SoundManager("sounds/GameOver.wav");
```m = new SoundManager```

2020-12-19 07:40 UTC, cagdasgerede commented on src/main/java/pl/nogacz/snake/board/Board.java
> +                        m= new SoundManager("sounds/GameOver.wav");
private final static String GAME_OVER_SOUND = "sounds/GameOver.wav"

2020-12-19 07:41 UTC, cagdasgerede commented on src/main/java/pl/nogacz/snake/board/Board.java
> +                        e.printStackTrace();
Bu tür exceptionlar Log dosyasina gitmeli

2020-12-19 07:41 UTC, cagdasgerede commented on src/main/java/pl/nogacz/snake/board/Board.java
> +                    }catch(Exception e){
```} catch```

2020-12-19 07:42 UTC, cagdasgerede commented on src/test/java/SnakeTest.java
> +            SoundManager s= new SoundManager("sounds/Iceland Theme.mp3");
```s = new```

2020-12-19 07:42 UTC, cagdasgerede commented on src/test/java/SnakeTest.java
> +            ex=true;
```ex = true```

2020-12-19 07:42 UTC, cagdasgerede commented on src/test/java/SnakeTest.java
> +    public void TestValidFormat(){
testValidFormat

2020-12-19 07:43 UTC, cagdasgerede commented on src/test/java/SnakeTest.java
> +    @Test
Bu testin format ile ne alakasi var?

Sanki burada yanlis dosya ismi verince exception atmasini bekliyorsun. Eger oyleyse bu test ismi cok dogru bir isim degil.

2020-12-19 07:43 UTC, cagdasgerede commented on src/test/java/SnakeTest.java
> +            SoundManager s=new SoundManager("sounds/a.wav");
fix spacing

2020-12-19 07:43 UTC, cagdasgerede commented on src/test/java/SnakeTest.java
> +            ex=true;
fix spacing

2020-12-19 07:46 UTC, cagdasgerede commented on src/test/java/SnakeTest.java
> +import org.junit.Assert;
Bu test şu testleri ekle

- play cagırılınca audioClip.start() cagırıldı mı
- loop cagırılınca audioClip.loop metodu Clip.LOOP_CONTINUOUSLY argumanı ıle cagırıldı mı
- stop cagırılınca audioClip.stop() cagırıldı mı

2020-12-19 07:51 UTC, cagdasgerede commented on src/main/java/pl/nogacz/snake/board/SoundManager.java
> +        this.path = path;
Buradaki constructor içeriğini bir metot içerisine al. Aksi halde bu classın bir objesini yaratmak için bir audio dosyasına ihtiyacın olur ve testten stream açmak zorunda kalırsın. Bunun yerine Testlerde SoundManager'dan yeni bir class override et ve yeni classta yeni metodu istediğin gibi override edebilirsin. Bu yaklaşım AudioInputStream vs. kodlarını test yaparken trigger etmeden obje yaratmanı sağlar.

2020-12-19 07:52 UTC, cagdasgerede commented on src/test/java/SnakeTest.java
> +public class SnakeTest {
Burada yalnızca SoundManager ile ilgili testler var. Bu dosyanın adı TestSoundManager.java olmalı (Tabii class ın adı da TestSoundManager olmalı)

2020-12-19 07:53 UTC, cagdasgerede commented on src/main/java/pl/nogacz/snake/board/Board.java
> +                        e.printStackTrace();
Bu tür exceptionlar Log dosyasına gitmeli.

2020-12-19 07:55 UTC, cagdasgerede requested changes
Kodda bıraktığım notlara göre kodunu güncelle.

2020-12-22 09:19 UTC, yasemindmrts commented on src/test/java/SnakeTest.java
> +    @Test
Hocam yazdığım kod sadece .wav uzantılı dosyaları çalıştırıyor. .mp3 uzantılı olanları çalıştırmıyor. sounds klasörüne mp3 uzantılı bir ses koymuştum. Doğru uzantılı olup olmadığını test etmiştim.

2021-03-22 23:56 UTC, closed without merging